### ISSUE TITLE
AttributeError: 'av.video.codeccontext.VideoCodecContext' object has no attribute 'close'

### ISSUE THREAD

**Issue by mnauf** [zju3dv/GVHMR#42]
I am running into a following issue after when I run `python tools/demo/demo.py --video=docs/example_video/tennis.mp4 -s`

```
12/28 16:15:08][INFO] [Input]: docs/example_video/tennis.mp4
[12/28 16:15:08][INFO] (L, W, H) = (312, 812, 720)
[12/28 16:15:08][INFO] [Output Dir]: outputs/demo/tennis
[12/28 16:15:08][INFO] [Copy Video] docs/example_video/tennis.mp4 -> outputs/demo/tennis/0_input_video.mp4
Copy: 100%|██████████████████████████████████| 312/312 [00:01<00:00, 168.51it/s]
[12/28 16:15:10][INFO] [GPU]: NVIDIA GeForce RTX 4070 Ti SUPER
[12/28 16:15:10][INFO] [GPU]: _CudaDeviceProperties(name='NVIDIA GeForce RTX 4070 Ti SUPER', major=8, minor=9, total_memory=15940MB, multi_processor_count=66)
[12/28 16:15:10][INFO] [Preprocess] Start!
YoloV8 Tracking: 100%|████████████████████████| 312/312 [00:07<00:00, 41.34it/s]
Traceback (most recent call last):
  File "/home/rob/Desktop/GVHMR/tools/demo/demo.py", line 289, in <module>
    run_preprocess(cfg)
  File "/home/rob/anaconda3/envs/gvhmr/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/rob/Desktop/GVHMR/tools/demo/demo.py", line 114, in run_preprocess
    vitpose = vitpose_extractor.extract(video_path, bbx_xys)
  File "/home/rob/anaconda3/envs/gvhmr/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/rob/Desktop/GVHMR/hmr4d/utils/preproc/vitpose.py", line 26, in extract
    imgs, bbx_xys = get_batch(video_path, bbx_xys, img_ds=img_ds)
  File "/home/rob/Desktop/GVHMR/hmr4d/utils/preproc/vitfeat_extractor.py", line 15, in get_batch
    imgs = read_video_np(input_path, scale=img_ds)
  File "/home/rob/Desktop/GVHMR/hmr4d/utils/video_io_utils.py", line 40, in read_video_np
    frames = iio.imread(video_path, plugin="pyav", filter_sequence=filter_args)
  File "/home/rob/anaconda3/envs/gvhmr/lib/python3.10/site-packages/imageio/v3.py", line 54, in imread
    return np.asarray(img_file.read(**call_kwargs))
  File "/home/rob/anaconda3/envs/gvhmr/lib/python3.10/site-packages/imageio/plugins/pyav.py", line 461, in read
    self._video_stream.close()
  File "av/video/stream.pyx", line 21, in av.video.stream.VideoStream.__getattr__
AttributeError: 'av.video.codeccontext.VideoCodecContext' object has no attribute 'close'

```

**Comment by zehongs** [comment]
There is no 'hands_meanl' in your `SMPLX_NEUTRAL.npz`. How did you get this file?

**Comment by ZhangYingHao7** [comment]
![image](https://github.com/user-attachments/assets/fbd95bd0-bdeb-4fb2-b10a-84ead6980dc9)

**Comment by ZhangYingHao7** [comment]
![image](https://github.com/user-attachments/assets/36af7538-db72-465f-b046-3da5a1492dc2)

**Comment by Shaun-Fong** [comment]
![Image](https://github.com/user-attachments/assets/bb5a3c68-7f34-4117-80e0-0aca09bd7611)

![Image](https://github.com/user-attachments/assets/21846b4a-7161-40f2-af66-69bbd440e972)

![Image](https://github.com/user-attachments/assets/08191093-3428-417c-8d4e-0be3dc3e5009)

![Image](https://github.com/user-attachments/assets/35bf3bf9-757e-4a1d-884c-f68aac8a3f47)

**Comment by Breezewrf** [comment]
> ![Image](https://github.com/user-attachments/assets/bb5a3c68-7f34-4117-80e0-0aca09bd7611)
> 
> ![Image](https://github.com/user-attachments/assets/21846b4a-7161-40f2-af66-69bbd440e972)
> 
> ![Image](https://github.com/user-attachments/assets/08191093-3428-417c-8d4e-0be3dc3e5009)
> 
> ![Image](https://github.com/user-attachments/assets/35bf3bf9-757e-4a1d-884c-f68aac8a3f47)

Correct, renaming is also necessary

**Comment by Calvinwork** [comment]
I have the same problem,have you solved it?
